version: "3"
services:
  redis:
    image: "redis:alpine"
#  mysql:
#    image: "mysql:5.7"
#    volumes:
#      - /Volumes/documents/server/database/mysql:/var/lib/mysql
  default:
    build: php56
    links:
      - redis
    ports:
      - 127.0.0.1:8081:80
    restart: always
    volumes:
      - /server/wwwroot:/var/www/html
