FROM debian:stretch-slim
MAINTAINER gouki <gouki.xiao@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /root

RUN \
  sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

RUN \
  apt-get update \
  && apt-get -y install --no-install-recommends wget apt-transport-https lsb-release ca-certificates\
  && wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
  && sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list' \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/apt/archive/*.deb /root/.cache/composer/*

RUN \
  buildDeps='busybox php7.2-common php7.2-opcache php7.2-mysql php7.2-curl php7.2-json php7.2-mbstring php7.2-xml ' \
  && apt-get update \
  && apt-get -y install --no-install-recommends  $buildDeps \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/apt/archive/*.deb /root/.cache/composer/*


