FROM gouki/php7
MAINTAINER gouki <gouki.xiao@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /root

RUN \
  buildDeps=' supervisor apache2 libapache2-mod-php7.2' \
  && apt-get update \
  && apt-get -y install --no-install-recommends  $buildDeps \
  && a2enmod rewrite \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/apt/archive/*.deb /root/.cache/composer/*




  
